(in-package :chillax)

;;;
;;; Server API
;;;

;; Server Protocol
(defgeneric server-host (server))
(defgeneric server-port (server))
(defgeneric server-username (server))
(defgeneric server-password (server))
(defgeneric server-secure-p (server))
(defgeneric data->json (server data &key)
  (:documentation "Converts DATA to JSON suitable for sending to CouchDB."))
(defgeneric json->data (server json &key)
  (:documentation "Converts JSON to the desired data structure."))
(defparameter +utf-8+ (make-external-format :utf-8 :eol-style :lf))
(defgeneric couch-request (server uri &key convert-data-p &allow-other-keys)
  (:documentation
   "Sends an HTTP request to the CouchDB server represented by SERVER. Most of the keyword arguments
 for drakma:http-request are available as kwargs for this message.")
  (:method (server uri &rest all-keys
            &key (content nil contentp) (convert-data-p t)
            &allow-other-keys)
    (remf all-keys :convert-data-p)
    (multiple-value-bind (response status-code)
        (apply #'http-request (strcat (server->url server) uri)
               :content-type "application/json"
               :external-format-out +utf-8+
               :basic-authorization (with-slots (username password) server
                                      (when username (list username password)))
               :content (cond ((and contentp convert-data-p)
                               (data->json server content))
                              ((and contentp (not convert-data-p))
                               content)
                              (t ""))
               all-keys)
      (values (json->data server response)
              (or (cdr (assoc status-code +status-codes+ :test #'=))
                  ;; The code should never get here once we know all the
                  ;; status codes CouchDB might return.
                  (error "Unknown status code: ~A. HTTP Response: ~A"
                         status-code response))))))

;; Server functions
(defun server->url (server)
  "Returns a string representation of the URL SERVER represents."
  (format nil "~A://~A:~A/"
          (if (server-secure-p server)
              "https"
              "http")
          (server-host server)
          (server-port server)))

(defun all-dbs (server)
  "Requests a list of all existing databases from SERVER."
  (couch-request server "_all_dbs"))

(defun config-info (server)
  "Requests the current configuration from SERVER."
  (couch-request server "_config"))

(defun replicate (server source target &key create-target-p continuousp
                  &aux (to-json `("source" ,source "target" ,target)))
  "Replicates the database in SOURCE to TARGET. SOURCE and TARGET can both be either database names
in the local server, or full URLs to local or remote databases. If CREATE-TARGET-P is true, the
target database will automatically be created if it does not exist. If CONTINUOUSP is true, CouchDB
will continue propagating any changes in SOURCE to TARGET."
  ;; There are some caveats to the keyword arguments -
  ;; create-target-p: doesn't actually seem to work at all in CouchDB 0.10
  ;; continuousp: The CouchDB documentation warns that this continuous replication
  ;;              will only last as long as the CouchDB daemon is running. If the
  ;;              daemon is restarted, replication must be restarted as well.
  ;;              Note that there are plans to add 'persistent' replication.
  (when create-target-p (setf to-json (append `("create_target" "true") to-json)))
  (when continuousp (setf to-json (append `("continuous" "true") to-json)))
  (couch-request server "_replicate" :method :post :content (format nil "{~{~s:~s~^,~}}" to-json)))

(defun stats (server)
  "Requests general statistics from SERVER."
  (couch-request server "_stats"))

(defun active-tasks (server)
  "Lists all the currently active tasks on SERVER."
  (couch-request server "_active_tasks"))

(defun get-uuids (server &key (number 10))
  "Returns a list of NUMBER unique IDs requested from SERVER. The UUIDs generated by the server are
reasonably unique, but are not checked against existing UUIDs, so conflicts may still happen."
  (couch-request server (format nil "_uuids?count=~A" number)))
